export const LoginType = {
    REQUEST_LOGIN: "REQUEST_LOGIN",
    REQUEST_LOGIN_SUCCESS: "REQUEST_LOGIN_SUCCESS",
    REQUEST_LOGIN_FAILED: "REQUEST_LOGIN_FAILED",
}
export const HistoryType = {
    REQUEST_HISTORY: "REQUEST_HISTORY",
    REQUEST_HISTORY_SUCCESS: "REQUEST_HISTORY_SUCCESS",
    REQUEST_HISTORY_FAILED: "REQUEST_HISTORY_FAILED",
}